#  3 Understanding your data II - Data Manipulations and feature engineering

1 Create and Load data
2 Data manipulations: slicing, reshaping and aggregations
3 Feature engineering: Tricks

In [3]:
#Create numpy array
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
x4 = np.arange(10)
#Create pd Series - x.values is a np array
x = pd.Series([1,2,3],index=['a','b','c'])
x1 = pd.Series({'a':1,'b':2,'c':3})
#Create pandas data frames
y = pd.DataFrame({'x':x,'x1':x1})
pd.DataFrame(np.random.rand(3, 2),columns=['foo', 'bar'],index=['a', 'b', 'c'])


In [ ]:
#Indexing numpy array
x4[:5] #Elements after index 5
x4[::2] #Every other element
x4[1::2] #starting from index 1,every other element
x4[5::-2] # reversed every other from index 5
#Similar for multiarrays
x2[::-1,::-1]
#Slicing in Series
#First, the loc attribute allows indexing and slicing that always references the explicit index
#The iloc attribute allows indexing and slicing that always references the implicit
#Python-style index
#The ix indexer allows a hybrid of these two approaches

In [ ]:
#One important—and extremely useful—thing to know about array slices is that 
#they return views rather than copies of the array data. If we modify the views, original data will change
#if we want to copy:
x2_sub_copy = x2[:2, :2].copy() 
print(x2_sub_copy)

In [5]:
#Reshape
grid = np.arange(1, 10).reshape((3, 3)) 
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
grid = np.concatenate([x, y]) # concatenate on rows
np.concatenate([grid, grid], axis=1) # concatenate on columns
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]]) # vertically stack the arrays
np.vstack([x, grid])
y = np.array([99],
            [99])
np.hstack([grid,y])

In [ ]:
#Splitting
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
left, right = np.hsplit(grid, [2])

In [ ]:
#Aggregates and sorting
x = np.arange(1, 6)
np.add.reduce(x)
np.multiply.reduce(x)
np.add.accumulate(x)
np.multiply.accumulate(x)
x = np.array([2, 1, 4, 3, 5])
np.sort(x)
i = np.argsort(x) #returns the indices of the sorted array
j = np.partition(x, 3) #returns the smallest 3 
#Others
#np.sum, np.prod,np.mean,np.std,np.var,np.min,np.max,np.argmin,np.median,np.percentile,np.any,np.all
#note that if we add nan, it will be the NaN safe version: eg np.nansum

In [ ]:
#Other useful functions
indices = np.random.choice(X.shape[0], 20, replace=False) #random selection

data.values will give a numpy array for a pd.Series

In [ ]:
import pandas as pd
#Data Frame in pandas could be considered as a sequence of aligned Series objects. Aligned means that 
#they share the same index
#Example 1
population_dict = {'California': 38332521,
                               'Texas': 26448193,
                               'New York': 19651127,
                               'Florida': 19552860,
                               'Illinois': 12882135}
population = pd.Series(population_dict)
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
states = pd.DataFrame({'population': population,
                                   'area': area})
states
#Example 2
test1 = pd.Series([1,2,3,4])
test2 = pd.Series([5,6,7,8])
test = pd.DataFrame({'feature1':test1,'feature2':test2})
test

In [ ]:
#Convert between Index and columns in pandas
tick = pd.Series(['2013','2014','2015'])
tag = pd.Series(['A','B','C'])
obs = pd.Series([2,2,6])
val = pd.Series([0.01,0.02,0.03])
df = pd.DataFrame({'tick':tick,'tag':tag,'obs':obs,'val':val})
df = df.set_index([df['tick'],df['tag'],df['obs']])
df = df.drop('tick',1)
df = df['val']
df = df.reset_index(level=['tick','obs'])
df

In [ ]:
#Concatenation with joins
pd.concat([df5, df6], join='inner') # only common columns, default is outjoin with NA filled in
pd.concat([df5, df6], join_axes=[df5.columns])
pd.concat([df5, df6], join_axes=[df5.columns])
df1.append(df2)

In [ ]:
#merge and join
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],'hire_date': [2004, 2008, 2012, 2014]})
df3 = pd.merge(df1, df2)
pd.merge(df1, df2, on='employee')
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)
pd.merge(df6, df7, how='outer')
pd.merge(df6, df7, how='left')

In [ ]:
#Example
#Read data
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')
print(pop.head()); print(areas.head()); print(abbrevs.head())
#Merge data
merged = pd.merge(pop, abbrevs, how='outer',left_on='state/region', right_on='abbreviation')
merged = merged.drop('abbreviation', 1) # drop duplicate info 
merged.head()
#Check missing
merged.isnull().any()
merged[merged['population'].isnull()].head()
merged.loc[merged['state'].isnull(), 'state/region'].unique()
#Fix missing
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()
#Repeat for another data source
final = pd.merge(merged, areas, on='state', how='left')
final.head()
final.isnull().any()
final['state'][final['area (sq. mi)'].isnull()].unique()
final.dropna(inplace=True) #why inplace has to be set as True?
final.head()
# data slicing
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()
# Compute population density
data2010.set_index('state', inplace=True)
density = data2010['population'] / data2010['area (sq. mi)']
#Sort
density.sort_values(ascending=False, inplace=True)
density.head()
density.tail()


In [ ]:
#Aggregation,Grouping and Filtering
#Aggregation
planets.dropna().describe()
df.groupby('key').aggregate({'data1': 'min','data2': 'max'})
#Filtering
def filter_func(x):
    return x['data2'].std() > 4
df.groupby('key').filter(filter_func)
#Transformation
df.groupby('key').transform(lambda x: x - x.mean())
#Apply - ?
def norm_by_data2(x):
# x is a DataFrame of group values
    x['data1'] /= x['data2'].sum() return x
print(df); print(df.groupby('key').apply(norm_by_data2))
#

In [ ]:
#String operations
#Nearly all Python’s built-in string methods are mirrored by a Pandas vectorized string method. Here is a list of Pandas str methods that mirror Python string methods:
#len() lower() ljust() upper() rjust() find() center() 
#rfind() zfill() index() strip() rindex() rstrip() capitalize() lstrip() swapcase()
#translate() startswith() endswith() isalnum() isalpha() isdigit() isspace()
#istitle() islower() isupper() isnumeric() isdecimal() split() rsplit() partition() rpartition()
monte.str.extract('([A-Za-z]+)')
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')
recipes.description.str.contains('[Bb]reakfast').sum()
#More string manipulations in python or pandas? 
selection = spice_df.query('parsley & paprika & tarragon')
recipes.name[selection.index]

In [ ]:
#Time series
dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015',
                                   '2015-Jul-6', '07-07-2015', '20150708']) #could specific format same as in R
dates.to_period('D')
pd.date_range('2015-07-03', periods=8, freq='H')
pd.period_range('2015-07', periods=8, freq='M')
pd.timedelta_range(0, periods=10, freq='H')
pd.timedelta_range(0, periods=9, freq="2H30T")

goog.plot(alpha=0.5, style='-')
goog.resample('BA').mean().plot(style=':')
goog.asfreq('BA').plot(style='--');
plt.legend(['input', 'resample', 'asfreq'],loc='upper left');

fig, ax = plt.subplots(2, sharex=True)
data = goog.iloc[:10]
data.asfreq('D').plot(ax=ax[0], marker='o')
data.asfreq('D', method='bfill').plot(ax=ax[1], style='-o')
data.asfreq('D', method='ffill').plot(ax=ax[1], style='--o')
ax[1].legend(["back-fill", "forward-fill"]);

#Use time shift to compute returns
ROI = 100 * (goog.tshift(-365) / goog - 1)
ROI.plot()
plt.ylabel('% Return on Investment');

#Rolling window
rolling = goog.rolling(365, center=True)
data = pd.DataFrame({'input': goog,'one-year rolling_mean': rolling.mean(),'one-year rolling_std': rolling.std()})
ax = data.plot(style=['-', '--', ':'])
ax.lines[0].set_alpha(0.3)

In [ ]:
#Example
# !curl -o FremontBridge.csv
# https://data.seattle.gov/api/views/65db-xm6k/rows.csv?accessType=DOWNLOAD
data = pd.read_csv('FremontBridge.csv', index_col='Date', parse_dates=True)
data.head()
data.columns = ['West', 'East']
data['Total'] = data.eval('West + East')
data.dropna().describe()
#
weekly = data.resample('W').sum()
weekly.plot(style=[':', '--', '-'])
plt.ylabel('Weekly bicycle count');
#
daily = data.resample('D').sum()
daily.rolling(30, center=True).sum().plot(style=[':', '--', '-'])
plt.ylabel('mean hourly count');
daily.rolling(50, center=True,win_type='gaussian').sum(std=10).plot(style=[':', '--', '-']);
#
by_time = data.groupby(data.index.time).mean()
hourly_ticks = 4 * 60 * 60 * np.arange(6)
by_time.plot(xticks=hourly_ticks, style=[':', '--', '-']);
#
by_weekday = data.groupby(data.index.dayofweek).mean()
by_weekday.index = ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun']
by_weekday.plot(style=[':', '--', '-']);
#
weekend = np.where(data.index.weekday < 5, 'Weekday', 'Weekend')
by_time = data.groupby([weekend, data.index.time]).mean()
#
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 2, figsize=(14, 5)) by_time.ix['Weekday'].plot(ax=ax[0], title='Weekdays',xticks=hourly_ticks, style=[':', '--', '-'])
by_time.ix['Weekend'].plot(ax=ax[1], title='Weekends',xticks=hourly_ticks, style=[':', '--', '-']);


In [ ]:
#High-Performance Pandas: eval() and query() - Need more readings
result1 = -df1 * df2 / (df3 + df4) - df5
result2 = pd.eval('-df1 * df2 / (df3 + df4) - df5')
#
result1 = (df1 < 0.5) & (df2 < 0.5) | (df3 < df4)
result2 = pd.eval('(df1 < 0.5) & (df2 < 0.5) | (df3 < df4)')
#
df.eval('D = (A + B) / C', inplace=True)
